server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.100.13.87:3306/pmcore?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: orangesoft
    password: orangesoft

mybatis:
  type-aliases-package: cn.edu.xjtu.stu.orangesoft.backdoor.bean
  mapper-locations: classpath:mapping/*Mapping.xml


